[package]
name = "apurri-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
rusqlite = "0.32.1"
scraper = "0.12"
tokio = { version = "1", features = ["full"] }
